- hosts: all
  become: yes

- hosts: all
  become: yes
  become_user: root
  vars_files:
    - vars/main.yml
  roles:
    - role: docker
      set_registry: yes
      registry: registry.crptech.local:80
      tags: [master, slave, docker]
    - role: group-hosts-to-hosts
      group: k8s-cluster
    - role: k8s/common
      tags: [master, slave]

- hosts: k8s-master
  become: yes
  become_user: root
  vars_files:
    - vars/main.yml
  roles:
    - role: k8s/master
      tags: master
    - role: k8s/accounts
      tags: accounts

- hosts: k8s-slaves
  become: yes
  become_user: root
  vars_files:
    - vars/main.yml
  roles:
    - role: k8s/slave
      tags: slave
